### ISSUE TITLE
AMM on 2 machines not communicating

### ISSUE THREAD

**Issue by ahamdy47** [AdvancedModularManikin/amm-library#1]
Hello keepers of AMM Repo. I am working on 2 machines (An Ubuntu that is running AMM core modules and a Win 10 that has the amm-library built and running the example module). I am having an issue connecting the 2. I know the Ubuntu is working correctly because I can see the Web Dashboard running and progressing, as well as the example module on the local machine (Ubuntu) works. Now when I try the example module on a different machine (Win 10) on the same LAN, it doesn't update any changes. I am using wireshark to troubleshoot this issue I have. I see RTPS packets are being sent from client to host but amm module-manager doesn't seem to detect it.

**Comment by riggs** [comment]
Is Windows firewall configured to allow RTPS traffic in (or disabled entirely)? Module connectivity is very-much bidirectional.

Edit: Specifically, RTPS relies on UDP broadcast between nodes on well-defined ports. Routers may also block UDP broadcast, or not forward between ports.

**Comment by ahamdy47** [comment]
![Capture](https://user-images.githubusercontent.com/25650280/88726975-a7933580-d0fc-11ea-8d5e-4692edd754e1.PNG)
Hello @riggs, thank you for the quick response. I am still having this issue. I attached an image of packets being sent on wireshark when I start the example module on my local machine (.75). The AMM core seems to be listening in on the data, but not updating the simulation state machine nor any related components of AMM. I am not sure if the issue is the protocol or some sort of config on either end.
