### ISSUE TITLE
Troubleshooting Build

### ISSUE THREAD

**Issue by victoria20001** [AdvancedModularManikin/amm-library#3]
Hello!

I'm wondering why the specfic file ( 'fastrtps/utils/eClock.h') wasn't built in the build for in amm-library?

I have all the dependencies downloaded.

Thank you!

![image](https://user-images.githubusercontent.com/78709838/109887255-3ee1dd80-7c36-11eb-9373-88dabed22447.png)

**Comment by riggs** [comment]
It looks like FastRTPS has been updated to be FastDDS. I suspect there may have been a version number bump in there as well that could be the culprit. @draum Do you know what the most recent working version number was?

**Comment by victoria20001** [comment]
Yes, FastDDS was originally Fast RTPS though in terms of filing name it's kinda the same (C:\Program Files\eProsima\fastrtps 2.2.0) I'm working with the latest version of FastDDS v2.2.0.

**Comment by draum** [comment]
Master has been updated to remove a no-longer-used header from FastRTPS / FastDDS.  This should now work with the latest versions of FastDDS.
